### ISSUE TITLE
Populate list of issues and plan 1st milestone work

### ISSUE THREAD

**Issue by SuperIzzo** [SuperIzzo/BattleDyzx#1]
This task may go hand in hand with some design work, which may spawn more tasks.
It is done when a planning session is completed and new tasks are entered and prioritised.

# Checklist
- [x] Create tasks
- [x] Set task priorities
- [x] Sort for first milestone
- [x] Estimate each task
- [x] #14
